<?php
return [
    'erp' => [
        'slug' => 'erp',
        'route' => 'erp-program',
        'title' => 'ERP & POS Management System',
        'short_title' => 'ERP & POS',
        'category' => 'Business System',
        'badge' => 'ERP · POS · OPERATIONS',
        'subtitle' => 'One connected workspace for daily business operations.',
        'description' => 'Manage sales, POS, inventory, purchasing, suppliers, expenses, accounting, reports, warehouses and branches from one practical system.',
        'image' => 'assets/images/programs/erp-system.png',
        'tags' => ['ERP', 'POS', 'Inventory', 'Accounting'],
        'features' => [
            ['POS & Sales', 'Fast checkout, invoices, payments and sales records in one flow.', 'fa-cash-register'],
            ['Inventory Control', 'Track products, stock levels, movements, warehouses and transfers.', 'fa-boxes-stacked'],
            ['Purchasing & Suppliers', 'Manage suppliers, purchase orders, invoices and receiving.', 'fa-truck-field'],
            ['Accounting', 'Chart of accounts, journals, ledger, trial balance and connected postings.', 'fa-scale-balanced'],
            ['Reports & Analytics', 'See operational and financial information without rebuilding reports manually.', 'fa-chart-line'],
            ['Branches & Permissions', 'Support multiple locations and control access by user role.', 'fa-building'],
        ],
        'highlights' => [
            ['Connected workflows', 'Sales, stock, purchasing and finance use the same business data.'],
            ['Warehouse visibility', 'Follow stock by warehouse and track transfers between locations.'],
            ['Bilingual ready', 'Structured for English and Arabic business workflows.'],
            ['Scalable structure', 'Suitable for growing shops, wholesalers and multi-branch operations.'],
        ],
        'audience' => ['Retail stores', 'Mini markets', 'Wholesalers', 'Warehouses', 'Multi-branch businesses', 'SMEs'],
    ],
    'car-rental' => [
        'slug' => 'car-rental',
        'route' => 'car-rental-program',
        'title' => 'Car Rental Management System',
        'short_title' => 'Car Rental',
        'category' => 'Business System',
        'badge' => 'FLEET · RENTALS · OPERATIONS',
        'subtitle' => 'Run the rental office from availability to return.',
        'description' => 'Control fleet availability, reservations, rentals, customers, invoices, payments, maintenance, insurance, registration, expenses and alerts.',
        'image' => 'assets/images/programs/car-rental-system.png',
        'tags' => ['Rental', 'Fleet', 'Invoices', 'Maintenance'],
        'features' => [
            ['Fleet Management', 'Keep vehicle details, status, photos, pricing and operational information together.', 'fa-car-side'],
            ['Reservations & Calendar', 'See availability clearly and prevent conflicting reservations.', 'fa-calendar-days'],
            ['Rental Contracts', 'Move reservations into rentals with customer, vehicle and pricing details connected.', 'fa-file-signature'],
            ['Invoices & Payments', 'Track rental totals, deposits, invoices, payments and remaining balances.', 'fa-receipt'],
            ['Maintenance', 'Record service work, oil changes, costs and insurance-covered maintenance.', 'fa-screwdriver-wrench'],
            ['Renewals & Alerts', 'Follow insurance, registration and other expiry dates before they become problems.', 'fa-bell'],
        ],
        'highlights' => [
            ['Live availability', 'Rental and reservation status affect whether a vehicle can be booked.'],
            ['Return workflow', 'Track actual return details and keep pricing connected to the rental.'],
            ['Cost control', 'Maintenance, insurance, registration and expenses remain visible beside rental income.'],
            ['Arabic & English', 'Designed for bilingual rental-office use.'],
        ],
        'audience' => ['Car rental offices', 'Small fleets', 'Multi-branch rentals', 'Vehicle leasing teams', 'Local agencies'],
    ],
    'ecommerce' => [
        'slug' => 'ecommerce',
        'route' => 'shoppingstore',
        'title' => 'E-commerce System',
        'short_title' => 'E-commerce',
        'category' => 'Web Application',
        'badge' => 'STORE · ORDERS · ADMIN',
        'subtitle' => 'A complete storefront with the management tools behind it.',
        'description' => 'A responsive commerce platform with product catalogs, cart, checkout, order management and an administration area.',
        'image' => 'assets/images/cards/Shopping-application.png',
        'tags' => ['Store', 'Cart', 'Orders', 'Admin'],
        'features' => [
            ['Product Catalog', 'Present products with structured details, pricing and media.', 'fa-box-open'],
            ['Shopping Cart', 'Keep the buying flow clear across desktop and mobile.', 'fa-cart-shopping'],
            ['Checkout', 'Collect customer and order information in a focused checkout experience.', 'fa-credit-card'],
            ['Order Management', 'Give administrators one place to review and manage incoming orders.', 'fa-clipboard-list'],
            ['Responsive Storefront', 'Layouts adapt cleanly to phones, tablets and desktop screens.', 'fa-mobile-screen-button'],
            ['Admin Control', 'Maintain store content and operations from a dedicated management area.', 'fa-user-gear'],
        ],
        'highlights' => [
            ['Custom workflow', 'The store can be adapted around the actual business instead of a generic plugin stack.'],
            ['Connected order data', 'Catalog, cart, checkout and administration share the same order flow.'],
            ['Mobile-first buying', 'Important actions remain easy to use on smaller screens.'],
            ['Expandable', 'The platform can grow with new catalog and operational requirements.'],
        ],
        'audience' => ['Retail brands', 'Local shops', 'Online sellers', 'Product businesses', 'Growing stores'],
    ],
    'agent-management' => [
        'slug' => 'agent-management',
        'route' => 'ams',
        'title' => 'Agent Management System',
        'short_title' => 'Agent Management',
        'category' => 'Management System',
        'badge' => 'AGENTS · CLIENTS · ACTIVITY',
        'subtitle' => 'Keep agent work visible and organized.',
        'description' => 'Manage agents, clients, schedules, assignments, records and operational activity from one central workspace.',
        'image' => 'assets/images/cards/ams-card.png',
        'tags' => ['Agents', 'Clients', 'Schedules', 'Reports'],
        'features' => [
            ['Agent Directory', 'Keep agent information and records in one searchable place.', 'fa-user-tie'],
            ['Client Records', 'Connect client information with the people and activity serving them.', 'fa-address-book'],
            ['Schedules', 'Organize appointments, shifts and planned activity more clearly.', 'fa-calendar-check'],
            ['Assignments', 'Give work to the right agent and keep responsibility visible.', 'fa-list-check'],
            ['Activity Tracking', 'Follow operational records instead of relying on scattered messages.', 'fa-clock-rotate-left'],
            ['Reporting', 'Review agent and operational information from structured system data.', 'fa-chart-column'],
        ],
        'highlights' => [
            ['Central workspace', 'Agents, clients and assignments stay connected.'],
            ['Clear responsibility', 'Teams can see who is responsible for each piece of work.'],
            ['Searchable history', 'Operational activity becomes easier to review later.'],
            ['Customizable', 'Fields and workflows can be adapted to the business process.'],
        ],
        'audience' => ['Sales teams', 'Service agencies', 'Field teams', 'Operations offices', 'Client-service businesses'],
    ],
    'project-management' => [
        'slug' => 'project-management',
        'route' => 'pms-program',
        'title' => 'Project Management System',
        'short_title' => 'Project Management',
        'category' => 'Management System',
        'badge' => 'PROJECTS · TASKS · TEAMS',
        'subtitle' => 'Turn projects into clear, trackable work.',
        'description' => 'Organize projects, tasks, teams, priorities and deadlines with a practical productivity-focused system.',
        'image' => 'assets/images/cards/pms-card.png',
        'tags' => ['Projects', 'Tasks', 'Teams', 'Deadlines'],
        'features' => [
            ['Projects', 'Keep project information, ownership and progress in one workspace.', 'fa-diagram-project'],
            ['Tasks', 'Break work into clear actions with status and responsibility.', 'fa-list-check'],
            ['Teams', 'Connect people to the projects and tasks they are working on.', 'fa-people-group'],
            ['Priorities', 'Make urgent and important work visible before it is missed.', 'fa-flag'],
            ['Deadlines', 'Track due dates and upcoming work from a central timeline.', 'fa-hourglass-half'],
            ['Progress', 'See what is moving, completed or blocked without rebuilding updates manually.', 'fa-bars-progress'],
        ],
        'highlights' => [
            ['One source of truth', 'Project information does not have to live across separate chats and notes.'],
            ['Clear ownership', 'Every task can have a visible responsible person.'],
            ['Better follow-up', 'Status and deadlines make delayed work easier to identify.'],
            ['Flexible workflow', 'The system can be adapted to different project types.'],
        ],
        'audience' => ['Development teams', 'Agencies', 'Operations teams', 'Small businesses', 'Internal departments'],
    ],
    'sports-reservation' => [
        'slug' => 'sports-reservation',
        'route' => 'sms',
        'title' => 'Sports Reservation System',
        'short_title' => 'Sports Reservation',
        'category' => 'Reservation System',
        'badge' => 'BOOKINGS · SLOTS · FACILITIES',
        'subtitle' => 'Make sports-facility booking clear for staff and customers.',
        'description' => 'A booking system for sports facilities with time-slot reservations, schedule control and customer-facing availability.',
        'image' => 'assets/images/cards/srs-card.png',
        'tags' => ['Bookings', 'Schedules', 'Facilities', 'Customers'],
        'features' => [
            ['Facility Management', 'Organize courts, fields or reservable spaces from one system.', 'fa-location-dot'],
            ['Time Slots', 'Control available booking times without overlapping reservations.', 'fa-clock'],
            ['Reservations', 'Keep customer bookings and schedule information connected.', 'fa-calendar-plus'],
            ['Availability', 'Show customers when a facility is available before they request a booking.', 'fa-calendar-day'],
            ['Customer Records', 'Keep contact and booking history available to staff.', 'fa-users'],
            ['Schedule Control', 'Give administrators a practical view of upcoming bookings.', 'fa-table-list'],
        ],
        'highlights' => [
            ['Fewer conflicts', 'Availability is driven by the booking schedule.'],
            ['Clear customer flow', 'Visitors can understand available times before booking.'],
            ['Central calendar', 'Staff can review upcoming facility usage in one place.'],
            ['Adaptable facilities', 'Suitable for different sports and reservation models.'],
        ],
        'audience' => ['Football fields', 'Padel courts', 'Gyms', 'Sports clubs', 'Training facilities'],
    ],
    'ocr' => [
        'slug' => 'ocr',
        'route' => 'OCR',
        'title' => 'Optical Character Recognition',
        'short_title' => 'OCR',
        'category' => 'Utility Application',
        'badge' => 'OCR · DOCUMENTS · TEXT',
        'subtitle' => 'Turn text inside images into usable digital content.',
        'description' => 'Extract text from images and documents with a streamlined interface designed for practical OCR workflows.',
        'image' => 'assets/images/cards/ocr-card.png',
        'tags' => ['OCR', 'Documents', 'Automation', 'Text'],
        'features' => [
            ['Image Input', 'Work with image-based content that contains text.', 'fa-image'],
            ['Text Extraction', 'Convert visible text into editable digital text.', 'fa-file-lines'],
            ['Document Workflow', 'Reduce repetitive retyping when information arrives as scans or photos.', 'fa-file-arrow-up'],
            ['Copy & Reuse', 'Use extracted text in other systems, documents or workflows.', 'fa-copy'],
            ['Focused Interface', 'Keep the extraction process simple and direct.', 'fa-wand-magic-sparkles'],
            ['Automation Ready', 'OCR output can become the first step in larger data-entry workflows.', 'fa-gears'],
        ],
        'highlights' => [
            ['Less manual typing', 'Useful when text arrives inside photos or scanned documents.'],
            ['Searchable content', 'Extracted text can be copied, searched and processed.'],
            ['Practical workflow', 'The interface focuses on the core OCR task.'],
            ['Expandable', 'Can be connected to broader document-processing systems.'],
        ],
        'audience' => ['Offices', 'Document teams', 'Data-entry workflows', 'Archives', 'Administrative operations'],
    ],
    'portfolio' => [
        'slug' => 'portfolio',
        'route' => 'portfolio-program',
        'title' => 'Portfolio Website',
        'short_title' => 'Portfolio',
        'category' => 'Website',
        'badge' => 'PORTFOLIO · FRONTEND · MOTION',
        'subtitle' => 'A personal portfolio built to present work as an experience.',
        'description' => 'A premium personal portfolio experience with responsive sections, motion and an interactive Three.js journey designed to present work professionally.',
        'image' => 'assets/images/brand-pattern-teal.png',
        'tags' => ['Portfolio', 'Frontend', 'Three.js', 'Responsive'],
        'live_display_url' => '',
        'features' => [
            ['Responsive Layout', 'The experience adapts from large desktop screens down to mobile.', 'fa-display'],
            ['Motion Design', 'Subtle reveal, navigation and content motion make the site feel intentional.', 'fa-wand-magic-sparkles'],
            ['Three.js Journey', 'An interactive visual section gives the portfolio a distinctive technical identity.', 'fa-cube'],
            ['Project Presentation', 'Work, services and milestones are organized into focused sections.', 'fa-briefcase'],
            ['Personal Brand', 'Typography, color and imagery are built around one consistent identity.', 'fa-fingerprint'],
            ['Project Showcase', 'Work samples can be organized into a focused, branded presentation.', 'fa-arrow-up-right-from-square'],
        ],
        'highlights' => [
            ['Actual supplied website', 'The live display uses the portfolio HTML provided for this project.'],
            ['Device preview', 'Visitors can switch the preview shell between desktop, tablet and mobile sizes.'],
            ['Interactive presentation', 'The portfolio is more than a static list of projects.'],
            ['Direct exit', 'Closing the live display returns visitors to the Programs page.'],
        ],
        'audience' => ['Developers', 'Freelancers', 'Creative professionals', 'Founders', 'Personal brands'],
    ],
];
